import 'dart:convert';

import '../../domain/repositories/categoria_repository.dart';
import '../../domain/repositories/plato_repository.dart';
import '../../domain/repositories/recordatorio_repository.dart';
import '../../domain/repositories/restaurante_repository.dart';

/// Current shape version of the JSON payload produced by
/// [exportDatabaseToJson]. Bump this if the shape changes in a way that
/// would break older readers.
const backupFormatVersion = 1;

/// Builds a full JSON dump of the database: every restaurant with its tags,
/// dishes, reminders and custom categories.
///
/// Shares the same "restaurantes" root shape as `assets/seed_restaurantes.json`
/// (see seed_loader.dart) plus the fields the one-time seed doesn't need
/// (recordatorios, categorias, plato comentario).
Future<String> exportDatabaseToJson({
  required RestauranteRepository restaurantes,
  required PlatoRepository platos,
  required RecordatorioRepository recordatorios,
  required CategoriaRepository categorias,
}) async {
  final lista = await restaurantes.watchAll().first;

  final restaurantesJson = <Map<String, dynamic>>[];
  for (final restaurante in lista) {
    final tags = await restaurantes.watchTagsFor(restaurante.id).first;
    final platosDelRestaurante = await platos.watchByRestaurante(restaurante.id).first;
    final recordatoriosDelRestaurante =
        await recordatorios.watchByRestaurante(restaurante.id).first;
    final categoriasDelRestaurante =
        await categorias.watchByRestaurante(restaurante.id).first;

    restaurantesJson.add({
      'nombre': restaurante.nombre,
      'ubicacion': restaurante.ubicacion,
      'notas': restaurante.notas,
      'visitas': restaurante.visitas,
      'tags': tags.map((t) => t.nombre).toList(),
      'platos': platosDelRestaurante
          .map((p) => {
                'tipo': p.tipo,
                'nombre': p.nombre,
                'puntuacion': p.puntuacion,
                'comentario': p.comentario,
              })
          .toList(),
      'recordatorios': recordatoriosDelRestaurante
          .map((r) => {'texto': r.texto, 'hecho': r.hecho})
          .toList(),
      'categorias': categoriasDelRestaurante
          .map((c) => {'nombre': c.nombre, 'orden': c.orden})
          .toList(),
    });
  }

  final payload = {
    'version': backupFormatVersion,
    'exportedAt': DateTime.now().toIso8601String(),
    'restaurantes': restaurantesJson,
  };

  return const JsonEncoder.withIndent('  ').convert(payload);
}

/// How many rows of each kind got added by [importDatabaseFromJson].
class ImportSummary {
  final int restaurantes;
  final int platos;
  final int recordatorios;
  final int categorias;

  const ImportSummary({
    required this.restaurantes,
    required this.platos,
    required this.recordatorios,
    required this.categorias,
  });
}

/// Parses [raw] (the same shape [exportDatabaseToJson] produces) and inserts
/// every restaurant as a brand new row, with fresh UUIDs generated by each
/// repository's `insert` (see lib/core/ids.dart). No attempt is made to
/// match or merge with existing data — importing the same file twice creates
/// duplicates, same philosophy as the one-time seed import in
/// seed_loader.dart.
Future<ImportSummary> importDatabaseFromJson(
  String raw, {
  required RestauranteRepository restaurantes,
  required PlatoRepository platos,
  required RecordatorioRepository recordatorios,
  required CategoriaRepository categorias,
}) async {
  final data = jsonDecode(raw) as Map<String, dynamic>;
  final lista = ((data['restaurantes'] as List?) ?? const [])
      .cast<Map<String, dynamic>>();

  var platosCount = 0;
  var recordatoriosCount = 0;
  var categoriasCount = 0;

  for (final item in lista) {
    final id = await restaurantes.insert(
      nombre: item['nombre'] as String,
      ubicacion: item['ubicacion'] as String?,
      notas: item['notas'] as String?,
      tags: ((item['tags'] as List?) ?? const []).cast<String>(),
      visitas: (item['visitas'] as num?)?.toInt() ?? 0,
    );

    final platosDelRestaurante =
        ((item['platos'] as List?) ?? const []).cast<Map<String, dynamic>>();
    for (final plato in platosDelRestaurante) {
      await platos.insert(
        restauranteId: id,
        tipo: plato['tipo'] as String,
        nombre: plato['nombre'] as String,
        puntuacion: (plato['puntuacion'] as num).toDouble(),
        comentario: plato['comentario'] as String?,
      );
      platosCount++;
    }

    final recordatoriosDelRestaurante = ((item['recordatorios'] as List?) ?? const [])
        .cast<Map<String, dynamic>>();
    for (final recordatorio in recordatoriosDelRestaurante) {
      final recordatorioId = await recordatorios.insert(
        restauranteId: id,
        texto: recordatorio['texto'] as String,
      );
      if (recordatorio['hecho'] == true) {
        await recordatorios.setHecho(recordatorioId, true);
      }
    }
    recordatoriosCount += recordatoriosDelRestaurante.length;

    final categoriasDelRestaurante = ((item['categorias'] as List?) ?? const [])
        .cast<Map<String, dynamic>>();
    for (final categoria in categoriasDelRestaurante) {
      await categorias.insert(
        restauranteId: id,
        nombre: categoria['nombre'] as String,
      );
    }
    categoriasCount += categoriasDelRestaurante.length;
  }

  return ImportSummary(
    restaurantes: lista.length,
    platos: platosCount,
    recordatorios: recordatoriosCount,
    categorias: categoriasCount,
  );
}
